using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    public partial class AddPackageFreeTrialDays : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "SubscriptionPackages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Key" character varying(40) NOT NULL,
                    "Name" character varying(80) NOT NULL,
                    "MonthlyPriceJmd" bigint NOT NULL,
                    "DisplayOrder" integer NOT NULL,
                    "IsCustom" boolean NOT NULL DEFAULT false,
                    "DiscountEnabled" boolean NOT NULL DEFAULT false,
                    "DiscountPercent" numeric NOT NULL DEFAULT 0,
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now()
                );

                ALTER TABLE "SubscriptionPackages" ADD COLUMN IF NOT EXISTS "FreeTrialDays" integer NOT NULL DEFAULT 14;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionPackages_Key"
                    ON "SubscriptionPackages" ("Key");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "FreeTrialDays",
                table: "SubscriptionPackages");
        }
    }
}
